### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by istudyatuni** [istudyatuni/weather-site#2]
Add theme toggle with following options:

- light
- dark, [~pallet 1~](https://colorhunt.co/palette/35394126282b5f85db90b8f8), [pallet 2](https://colorhunt.co/palette/4c5f7a393e6f3d2e4f321d2f)
- system

https://colorffy.com/dark-theme-generator

**Comment by muralidhar3112** [comment]
Hi! I'm new to opensource, i wanna try it out. Can i please contribute to this issue!

**Comment by istudyatuni** [comment]
Hello, I already did it, just not pushed, because wanna support "system" theme
